### ISSUE TITLE
Dicussion about user model

### ISSUE THREAD

**Issue by leiverandres** [labsirius/SiriusWebProject#31]
@aerendon @sebasvega95 
In the user model there is a field called _privilegeType,_ which basically refers to the status of the user: pending, admin, user accepted and inactive. Also there is a field called _status_ which refers to the user rol within Sirius. Thus I propose the following changes:

* Change privilegeType name for status or state
* Change status name for rol or position

**Comment by aerendon** [comment]
I have a question ... the modification of existing fields does not affect the DB that is in production?
___

The new proposal is that the user profile is CV.
Some interesting fields could be:
* Photo
* Resume
* Skills
* Education
* Courses
* Projects
* Portfolio
* Papers
* Others...

**Comment by leiverandres** [comment]
This will be the new model for users:
```
user: {
  _id: string,
  username: string,
  firstName: string,
  lastName: string,
  profession?: string,
  role?: string,
  socialNetworks?: {
    facebook?: string,
    twitter?: string,
    linkedin?: string,
    github?: string,
    youtube?: string
  },
  phoneNumber?: string,
  email: string,
  website?: string,
  education?: [
    {
      title: string,
      institute: string,
      startYear: int,
      endYear?: int,
      description: string
    }, ...
  ],
  description?: string,
  papers?: [
    {
      date: Date,
      title: string,
      publisher: string,
      url: string
    }, ...
  ],
  skills?: [
    {
      name: string,
      level: int
    }, ...
  ],
  projects?: [
    ProjectModel, ...
  ]
}
```
